### ISSUE TITLE
Exception: org.postgresql.util.PSQLException: ERROR: canceling statement due to user request

### ISSUE THREAD

**Issue by crystalfp** [d2rq/d2rq#272]
My first few minutes of exposure to D2R.
PostgreSQL database V9.3.10 (with 40 tables) with D2R 0.8.1 on Ubuntu 14.04
I tried few accesses from the start page http://localhost:2020/ with no problems. Then attempted SPARQL query from http://localhost:2020/snorql (the one provided as "Properties" link on the right)

```
SELECT DISTINCT ?property
WHERE { [] ?property [] }
ORDER BY ?property 
```

After few seconds the following appears in the query frame:
`org.postgresql.util.PSQLException: ERROR: canceling statement due to user request`

(well, I don't have requested anything...)

And the server starts outputting  these lines:

```
13:19:00 WARN  QueryIteratorCheck   :: Open iterator: QueryIterRoot/83
13:19:00 WARN  QueryIteratorCheck   :: Open iterator: OpUnionTableSQL$1/84
13:19:00 WARN  QueryIteratorCheck   :: Open iterator: QueryIterConcat/88
13:19:00 WARN  QueryIteratorCheck   :: Open iterator: QueryIterTableSQL/115
13:19:00 WARN  QueryIteratorCheck   :: Open iterator: QueryIterTableSQL/116
13:19:00 WARN  QueryIteratorCheck   :: Open iterator: QueryIterTableSQL/117
... and much more like this ...
```

Then the only possibility is to kill and restart the server to be able to make another query.

Anything to try to understand what happens?
Thanks for your help!
mario

**Comment by crystalfp** [comment]
OK, seems related to timeout.
Now increasing sparqlTimeout to 6000 in the mapping file the error changes to the following (server started with --verbose --fast):

```
14:48:32 INFO  SPARQL               :: Throwable: GC overhead limit exceeded
java.lang.OutOfMemoryError: GC overhead limit exceeded
    at java.lang.String.toCharArray(String.java:2746)
    at java.util.zip.ZipCoder.getBytes(ZipCoder.java:78)
    at java.util.zip.ZipFile.getEntry(ZipFile.java:306)
    at java.util.jar.JarFile.getEntry(JarFile.java:227)
    at java.util.jar.JarFile.getJarEntry(JarFile.java:210)
    at sun.misc.URLClassPath$JarLoader.getResource(URLClassPath.java:840)
    at sun.misc.URLClassPath.getResource(URLClassPath.java:199)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:358)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:412)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
    at java.util.ResourceBundle$Control.newBundle(ResourceBundle.java:2566)
    at java.util.ResourceBundle.loadBundle(ResourceBundle.java:1436)
    at java.util.ResourceBundle.findBundle(ResourceBundle.java:1400)
    at java.util.ResourceBundle.findBundle(ResourceBundle.java:1354)
    at java.util.ResourceBundle.findBundle(ResourceBundle.java:1354)
    at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1296)
    at java.util.ResourceBundle.getBundle(ResourceBundle.java:721)
    at org.postgresql.util.GT.<init>(GT.java:47)
    at org.postgresql.util.GT.<clinit>(GT.java:26)
    at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1818)
    at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:257)
    at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:512)
    at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:374)
    at org.postgresql.jdbc2.AbstractJdbc2Statement.executeQuery(AbstractJdbc2Statement.java:254)
    at de.fuberlin.wiwiss.d2rq.sql.SQLIterator.ensureQueryExecuted(SQLIterator.java:157)
    at de.fuberlin.wiwiss.d2rq.sql.SQLIterator.hasNext(SQLIterator.java:54)
    at de.fuberlin.wiwiss.d2rq.engine.QueryIterTableSQL.hasNextBinding(QueryIterTableSQL.java:90)
14:48:32 INFO  ResponseHttp         :: Error: URI = sparql : GC overhead limit exceeded
14:48:32 WARN  QueryIteratorCheck   :: Open iterator: QueryIterRoot/0
14:48:32 WARN  QueryIteratorCheck   :: Open iterator: OpUnionTableSQL$1/1
14:48:32 WARN  QueryIteratorCheck   :: Open iterator: QueryIterConcat/5
14:48:32 WARN  QueryIteratorCheck   :: Open iterator: QueryIterTableSQL/57
14:48:32 WARN  QueryIteratorCheck   :: Open iterator: QueryIterTableSQL/58
14:48:32 WARN  QueryIteratorCheck   :: Open iterator: QueryIterTableSQL/59
... continues ...
```

Don't think my database is so big!
Still learning...
Thanks for any help!
mario

**Comment by crystalfp** [comment]
Needs more investigation before opening an issue. Thanks!
