### ISSUE TITLE
 DESCRIBE SPARQL query to SNORQL endpoint

### ISSUE THREAD

**Issue by buxg** [d2rq/d2rq#281]
The DESCRIBE sparql query to D2R-SNORQL endpoint , as for example:

DESCRIBE ?x 
WHERE { ?x pgsc:farm_Id "1"} 

 do not return the rdf description of the required resource  but the rdf description of the namespaces involved in the rdf mapping of the db.

How to compose an alternative  Sparql query to obtain a  resource description?

**Comment by cygri** [comment]
It works fine for me. If I navigate to the page for some resource in D2R Server, then copy the resource's URI, then go to the Snorql interface and run a query such as:

```
DESCRIBE <URI_of_resource_here>
```

I get a description of the resource in RDF/XML.

If you get an empty RDF/XML file with just a bunch of `xmlns` namespace declarations, then the reason is likely that your query didn't return any results.

If your problem persists, please re-open with additional details.

**Comment by buxg** [comment]
I try the query
DESCRIBE http://localhost:8080/pgsc/resource/farm/1

but I have  a server internal error:

_Server internal error: can't write the model._.

**Comment by cygri** [comment]
Try

```
DESCRIBE <http://localhost:8080/pgsc/resource/farm/1>
```

URIs in SPARQL are always in pointy brackets, unless prefix-abbreviated (like `pgsc:farm_Id`)

The error message that you report doesn't look like a D2R Server error message. Please run your queries through the Snorql interface and report _exactly_ what error you get.

**Comment by buxg** [comment]
here in the following the complete error report on th SNORQL  interface:

Server internal error: can't write the model.

URI = sparql
com.hp.hpl.jena.shared.BadURIException: Only well-formed absolute URIrefs can be included in RDF/XML output:  Code: 57/REQUIRED_COMPONENT_MISSING in HOST: A component that is required by the scheme is missing.
    at com.hp.hpl.jena.xmloutput.impl.BaseXMLWriter.checkURI(BaseXMLWriter.java:846)
    at com.hp.hpl.jena.xmloutput.impl.BaseXMLWriter.relativize(BaseXMLWriter.java:823)
    at com.hp.hpl.jena.xmloutput.impl.Unparser.wURIreference(Unparser.java:893)
    at com.hp.hpl.jena.xmloutput.impl.Unparser.wURIreference(Unparser.java:897)
    at com.hp.hpl.jena.xmloutput.impl.Unparser.wResourceAttr(Unparser.java:963)
    at com.hp.hpl.jena.xmloutput.impl.Unparser.wResourceNodeIDAttr(Unparser.java:937)
    at com.hp.hpl.jena.xmloutput.impl.Unparser.wIdRefAttrOpt(Unparser.java:906)
    at com.hp.hpl.jena.xmloutput.impl.Unparser.wPropertyEltCompact(Unparser.java:384)
    at com.hp.hpl.jena.xmloutput.impl.Unparser.wPropertyElt(Unparser.java:351)
    at com.hp.hpl.jena.xmloutput.impl.Unparser.wPropertyEltStar(Unparser.java:823)
    at com.hp.hpl.jena.xmloutput.impl.Unparser.wTypedNodeOrDescriptionLong(Unparser.java:809)
    at com.hp.hpl.jena.xmloutput.impl.Unparser.wTypedNodeOrDescription(Unparser.java:739)
    at com.hp.hpl.jena.xmloutput.impl.Unparser.wTypedNode(Unparser.java:712)
    at com.hp.hpl.jena.xmloutput.impl.Unparser.wObj(Unparser.java:652)
    at com.hp.hpl.jena.xmloutput.impl.Unparser.wObjStar(Unparser.java:329)
    at com.hp.hpl.jena.xmloutput.impl.Unparser.wRDF(Unparser.java:310)
    at com.hp.hpl.jena.xmloutput.impl.Unparser.write(Unparser.java:212)
    at com.hp.hpl.jena.xmloutput.impl.Abbreviated.writeBody(Abbreviated.java:154)
    at com.hp.hpl.jena.xmloutput.impl.BaseXMLWriter.writeXMLBody(BaseXMLWriter.java:515)
    at com.hp.hpl.jena.xmloutput.impl.BaseXMLWriter.write(BaseXMLWriter.java:487)
    at com.hp.hpl.jena.xmloutput.impl.Abbreviated.write(Abbreviated.java:139)
    at com.hp.hpl.jena.xmloutput.impl.BaseXMLWriter.write(BaseXMLWriter.java:472)
    at org.joseki.http.HttpResultSerializer.writeModel(HttpResultSerializer.java:84)
    at org.joseki.http.ResponseHttp.doResponseModel(ResponseHttp.java:132)
    at org.joseki.Response.sendResponse(Response.java:84)
    at org.joseki.Dispatcher.dispatch(Dispatcher.java:60)
    at org.joseki.http.Servlet.doCommon(Servlet.java:178)
    at org.joseki.http.Servlet.doPost(Servlet.java:247)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:648)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
    at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:521)
    at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1096)
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:674)
    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1500)
    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1456)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
    at java.lang.Thread.run(Thread.java:745)

**Comment by buxg** [comment]
I just tried with the prefix abbreviated (pgfsc:farm_Id) and it works, by returning the top description of the retrieved resources (see below). How to obtain a complete description of the resource, including also the properties list?

<?xml version="1.0"?>
<rdf:RDF
    xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
    xmlns:pgsc="http://localhost:8080/pgsc/resource/pgsc/"
    xmlns:owl="http://www.w3.org/2002/07/owl#"
    xmlns:db="http://localhost:8080/pgsc/resource/"
    xmlns:d2r="http://sites.wiwiss.fu-berlin.de/suhl/bizer/d2r-server/config.rdf#"
    xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#"
    xmlns:meta="http://www4.wiwiss.fu-berlin.de/bizer/d2r-server/metadata#"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema#"
    xmlns:map="http://localhost:8080/pgsc/resource/#">
  <rdf:Description rdf:about="http://localhost:8080/pgsc/resource/farm/3">
    <pgsc:farm_Id rdf:datatype="http://www.w3.org/2001/XMLSchema#integer"
    >3/pgsc:farm_Id
  /rdf:Description
  <rdf:Description rdf:about="http://localhost:8080/pgsc/resource/farm/2">
    <pgsc:farm_Id rdf:datatype="http://www.w3.org/2001/XMLSchema#integer"
    >2/pgsc:farm_Id
  /rdf:Description
  <rdf:Description rdf:about="http://localhost:8080/pgsc/resource/farm/1">
    <pgsc:farm_Id rdf:datatype="http://www.w3.org/2001/XMLSchema#integer"
    >1/pgsc:farm_Id
  /rdf:Description
/rdf:RDF

**Comment by cygri** [comment]
Thanks. Looks like you have an issue in your mapping, and it generates URIs that are not valid. D2R Server reports an internal server error when it tries to write that invalid URI into the RDF/XML response. You need to fix your mapping. Try running `dump-rdf`. If that also generates an error, then remove parts of your mapping until the error disappears, to narrow down the problem.

The second query you tried returns all values of the `pgfsc:farm_Id` property, but that's not what you want.

**Comment by buxg** [comment]
The dump-rdf do not gives any error.
Here below the dump:

[dump_pgsc.txt](https://github.com/d2rq/d2rq/files/134172/dump_pgsc.txt)

**Comment by cygri** [comment]
Trying to parse this with Jena's `riot` tool:

```
11:53:38 WARN  riot                 :: [line: 60, col: 84] {W107} Bad URI: <http:\\www.facebook.com?user=3434534> Code: 57/REQUIRED_COMPONENT_MISSING in HOST: A component that is required by the scheme is missing.
11:53:38 WARN  riot                 :: [line: 61, col: 64] {W107} Bad URI: <http:\\www.puglia.it> Code: 57/REQUIRED_COMPONENT_MISSING in HOST: A component that is required by the scheme is missing.
11:53:38 WARN  riot                 :: [line: 62, col: 68] {W107} Bad URI: <http:\\www.aapuglianuova.it> Code: 57/REQUIRED_COMPONENT_MISSING in HOST: A component that is required by the scheme is missing.
```

Some of the URIs contain backslashes. Backslashes are not allowed in URIs. They should be forward slashes. You have various options for fixing this:
- Fix the original data in the database
- Generate string literals instead of URIs for this property
- Add a `d2rq:condition` to the property bridge that filters out values containing backslashes

**Comment by buxg** [comment]
After fixing the URIs as literal , the DESCRIBE query works well. I tried three alternative DESCRIBE queries:

1) DESCRIBE http://localhost:8080/pgsc/resource/farm/1  
it generate the complete description of the resource, as I want;

2) DESCRIBE pgsc:farm  
it generate only the top description of each retrieved farm resource

3) DESCRIBE pgsc:farm_Id
it generates  the description of the farm_Id property of each farm resource

So , it seems that only a DESCRIBE query with the complete URI of a resource generates the complete description of the resource.

Does perhaps  didn't correctly specify  the prefix abbreviated specification of the complete URI?  It could be more user friendly to specify  a DESCRIBE query with a prefix abbreviated URI of a resource.

**Comment by cygri** [comment]
You can define a prefix in the mapping file like:

```
@prefix farm: <http://localhost:8080/pgsc/resource/farm/>.
```

This then allows you to abbreviate the URI `<http://localhost:8080/pgsc/resource/farm/1>` as `farm:1`. So you should be able to query:

```
DESCRIBE farm:1
```

Note that `pgsc:farm` is a _class_ (the class of all farms), so describing this resource will yield a list of all farms. And `pgsc:farm_Id` is a _property_, so describing it will yield the value of that property for all farms.

**Comment by buxg** [comment]
Excellent! It works fine!
Now I close this issue,  However i need to open another one, that is important for my project.
