### ISSUE TITLE
d2r-server fails to start due to java version with a component number greater than 255

### ISSUE THREAD

**Issue by gabrimonfa** [d2rq/d2rq#322]
OS: Debian Jessie

java -version

java version "1.7.0_261"
OpenJDK Runtime Environment (IcedTea 2.6.22) (7u261-2.6.22-1~deb8u1)
OpenJDK 64-Bit Server VM (build 24.261-b02, mixed mode)

d2r-server fails with the following error:

Exception in thread "main" java.lang.ExceptionInInitializerError
        at com.ibm.icu.impl.UPropertyAliases.<clinit>(UPropertyAliases.java:87)
        at com.ibm.icu.lang.UCharacter.<clinit>(UCharacter.java:5680)
        at com.hp.hpl.jena.iri.impl.AbsLexer.difficultCodePoint(AbsLexer.java:139)
        at com.hp.hpl.jena.iri.impl.AbsLexer.difficultChar(AbsLexer.java:224)
        at com.hp.hpl.jena.iri.impl.LexerQuery.yylex(LexerQuery.java:603)
        at com.hp.hpl.jena.iri.impl.AbsLexer.analyse(AbsLexer.java:53)
        at com.hp.hpl.jena.iri.impl.Parser.<init>(Parser.java:112)
...
Caused by: java.lang.IllegalArgumentException: Invalid version number: Version number may be negative or greater than 255
        at com.ibm.icu.util.VersionInfo.getInstance(VersionInfo.java:188)
        at com.ibm.icu.impl.ICUDebug.getInstanceLenient(ICUDebug.java:65)
        at com.ibm.icu.impl.ICUDebug.<clinit>(ICUDebug.java:69)

java version "1.7.0_181"
OpenJDK Runtime Environment (IcedTea 2.6.14) (7u181-2.6.14-1~deb8u1)
OpenJDK 64-Bit Server VM (build 24.181-b01, mixed mode)

All work correctly

**Comment by wesyah234** [comment]
We are seeing this exception as well when we upgraded from :
java-1.8.0-openjdk-1.8.0.252.b09-2
to:
java-1.8.0-openjdk-1.8.0.262.b10-0

we think this post:
https://issues.liferay.com/browse/LPS-117529
might address the issue.

This comment speaks to a solution:
This is due to a problem in a legacy third-party library ICU4j. The issue is resolved in ICU4j 4.3.4 milestone or later by updating ICUDebug.java:

    https://github.com/unicode-org/icu/blob/icu4j-milestone-4-3-3/main/classes/core/src/com/ibm/icu/impl/ICUDebug.java#L34-L65
    https://github.com/unicode-org/icu/blob/icu4j-milestone-4-3-4/main/classes/core/src/com/ibm/icu/impl/ICUDebug.java#L34-L67


Any thoughts/ updates on this issue?
Thanks!

**Comment by wesyah234** [comment]
We are seeing this exception as well when we upgraded from :
java-1.8.0-openjdk-1.8.0.252.b09-2
to:
java-1.8.0-openjdk-1.8.0.262.b10-0

we think this post:
https://issues.liferay.com/browse/LPS-117529
might address the issue.

This comment speaks to a solution:
This is due to a problem in a legacy third-party library ICU4j. The issue is resolved in ICU4j 4.3.4 milestone or later by updating ICUDebug.java:

    https://github.com/unicode-org/icu/blob/icu4j-milestone-4-3-3/main/classes/core/src/com/ibm/icu/impl/ICUDebug.java#L34-L65
    https://github.com/unicode-org/icu/blob/icu4j-milestone-4-3-4/main/classes/core/src/com/ibm/icu/impl/ICUDebug.java#L34-L67


Any thoughts/ updates on this issue?
Thanks!

**Comment by yishanchuan** [comment]
I met the same issues in openjdk-8-jdk.
Now I solve this by upgrade the jdk version to openjdk11-jdk.

**Comment by wesyah234** [comment]
Thanks, we'll give that a try.
