### ISSUE TITLE
Executing SPARQL queries against a ModelD2RQ- java error

### ISSUE THREAD

**Issue by chitra15** [d2rq/d2rq#324]
public static void main(String[] args) {	
	ModelD2RQ m = new ModelD2RQ("C:/Users/chitra.nundlall/Documents/Chitra/d2rq-0.8.1/d2rq-0.8.1/test.ttl");

	 String SparqlQuery2 = "PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> " + 
		        "PREFIX OntoDASD: <http://www.semanticweb.org/shweta/ontologies/2020/2/TaskAllocationAndCoordinationOntology#> "+
		   		"PREFIX owl: <http://www.w3.org/2002/07/owl#> " + 
		   		"PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> " + 
		   		"PREFIX xsd: <http://www.w3.org/2001/XMLSchema#> " + 
		   		"SELECT * WHERE  { ?s ?p ?o }" ;
	Query q = QueryFactory.create(SparqlQuery2); 
	ResultSet rs = QueryExecutionFactory.create(q, m).execSelect();
	m.close();
}
}

Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/log4j/Logger
	at de.fuberlin.wiwiss.d2rq.dbschema.DatabaseSchemaInspector.<clinit>(DatabaseSchemaInspector.java:34)
	at de.fuberlin.wiwiss.d2rq.sql.ConnectedDB.schemaInspector(ConnectedDB.java:243)
	at de.fuberlin.wiwiss.d2rq.sql.ConnectedDB.isNullable(ConnectedDB.java:268)
	at de.fuberlin.wiwiss.d2rq.algebra.Attribute.notNullExpression(Attribute.java:105)
	at de.fuberlin.wiwiss.d2rq.parser.RelationBuilder.buildRelation(RelationBuilder.java:148)
	at de.fuberlin.wiwiss.d2rq.map.PropertyBridge.buildRelation(PropertyBridge.java:204)
	at de.fuberlin.wiwiss.d2rq.map.PropertyBridge.toTripleRelations(PropertyBridge.java:214)
	at de.fuberlin.wiwiss.d2rq.map.ClassMap.compile(ClassMap.java:97)
	at de.fuberlin.wiwiss.d2rq.map.ClassMap.compiledPropertyBridges(ClassMap.java:89)
	at de.fuberlin.wiwiss.d2rq.map.Mapping.compilePropertyBridges(Mapping.java:203)
	at de.fuberlin.wiwiss.d2rq.map.Mapping.compiledPropertyBridges(Mapping.java:195)
	at de.fuberlin.wiwiss.d2rq.engine.TransformOpBGP.createOpD2RQ(TransformOpBGP.java:60)
	at de.fuberlin.wiwiss.d2rq.engine.TransformOpBGP.transform(TransformOpBGP.java:48)
	at com.hp.hpl.jena.sparql.algebra.op.OpBGP.apply(OpBGP.java:47)
	at com.hp.hpl.jena.sparql.algebra.Transformer$ApplyTransformVisitor.visit0(Transformer.java:272)
	at com.hp.hpl.jena.sparql.algebra.OpVisitorByType.visit(OpVisitorByType.java:41)
	at com.hp.hpl.jena.sparql.algebra.op.OpBGP.visit(OpBGP.java:49)
	at com.hp.hpl.jena.sparql.algebra.OpWalker$WalkerVisitor.visit0(OpWalker.java:86)
	at com.hp.hpl.jena.sparql.algebra.OpVisitorByType.visit(OpVisitorByType.java:41)
	at com.hp.hpl.jena.sparql.algebra.op.OpBGP.visit(OpBGP.java:49)
	at com.hp.hpl.jena.sparql.algebra.OpWalker.walk(OpWalker.java:52)
	at com.hp.hpl.jena.sparql.algebra.OpWalker.walk(OpWalker.java:42)
	at com.hp.hpl.jena.sparql.algebra.Transformer.applyTransformation(Transformer.java:110)
	at com.hp.hpl.jena.sparql.algebra.Transformer.transformation(Transformer.java:103)
	at com.hp.hpl.jena.sparql.algebra.Transformer.transformation(Transformer.java:92)
	at com.hp.hpl.jena.sparql.algebra.Transformer.transform(Transformer.java:53)
	at de.fuberlin.wiwiss.d2rq.engine.QueryEngineD2RQ.translate(QueryEngineD2RQ.java:80)
	at de.fuberlin.wiwiss.d2rq.engine.QueryEngineD2RQ.modifyOp(QueryEngineD2RQ.java:60)
	at com.hp.hpl.jena.sparql.engine.QueryEngineBase.createPlan(QueryEngineBase.java:94)
	at com.hp.hpl.jena.sparql.engine.QueryEngineBase.getPlan(QueryEngineBase.java:87)
	at de.fuberlin.wiwiss.d2rq.engine.QueryEngineD2RQ$QueryEngineFactoryD2RQ.create(QueryEngineD2RQ.java:110)
	at com.hp.hpl.jena.sparql.engine.QueryExecutionBase.getPlan(QueryExecutionBase.java:522)
	at com.hp.hpl.jena.sparql.engine.QueryExecutionBase.startQueryIterator(QueryExecutionBase.java:499)
	at com.hp.hpl.jena.sparql.engine.QueryExecutionBase.execResultSet(QueryExecutionBase.java:507)
	at com.hp.hpl.jena.sparql.engine.QueryExecutionBase.execSelect(QueryExecutionBase.java:216)
	at d2rq.main(d2rq.java:101)
Caused by: java.lang.ClassNotFoundException: org.apache.log4j.Logger
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 36 more

**Comment by tayloj** [comment]
> java.lang.NoClassDefFoundError: org/apache/log4j/Logger

Sounds like the log4j dependency is missing at runtime.

**Comment by chitra15** [comment]
> > java.lang.NoClassDefFoundError: org/apache/log4j/Logger
> 
> Sounds like the log4j dependency is missing at runtime.

@tayloj  thanks a lot... it worked... however am getting another error when running the following codes:
	public static void main(String[] args) {	
	ModelD2RQ m = new ModelD2RQ("C:/Users/chitra.nundlall/Documents/Chitra/d2rq-0.8.1/d2rq-0.8.1/test.ttl");

	 String SparqlQuery2 = "PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> " + 
		        "PREFIX OntoDASD: <http://www.semanticweb.org/shweta/ontologies/2020/2/TaskAllocationAndCoordinationOntology#> "+
		   		"PREFIX owl: <http://www.w3.org/2002/07/owl#> " + 
		   		"PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> " + 
		   		"PREFIX xsd: <http://www.w3.org/2001/XMLSchema#> " + 
		   		"SELECT * WHERE  { ?s ?p ?o }" ;
	Query q = QueryFactory.create(SparqlQuery2); 
	ResultSet rs = QueryExecutionFactory.create(q, m).execSelect();
	while (rs.hasNext()) {
	    QuerySolution row = rs.nextSolution();

	    **System.out.println("BacklogID: " + row.getLiteral("BacklogId").getString());**
//	    System.out.println("Author: " + row.getLiteral("authorName").getString());
	};
	m.close();
}
}

The line - ''**System.out.println("BacklogID: " + row.getLiteral("BacklogId").getString());**'' is causing the error below:

Exception in thread "main" java.lang.NullPointerException
	at d2rq.main(d2rq.java:105)


Grateful if you could help me on this one.

**Comment by tayloj** [comment]
In

    System.out.println("BacklogID: " + row.getLiteral("BacklogId").getString());

there are only two possible null pointer exceptions.  Either `row` is null (very unlikely)  or `row.getLiteral("BacklogId")` is returning null. Since your query has no variable `?BacklogId`, I expect that getLiteral is returning null.
